config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  post "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new" # The `new` route needs to be *before* `show` route.
  get "tasks/:id", to: "tasks#show", as: :task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(restaurant_params)
    @task.save
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(restaurant_params)
    redirect_to tasks_path
  end

def destroy
    @task = Task.find(params[:id])
    @task.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

private

  def restaurant_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Task Manager</h1>

<ul>
  <% @tasks.each do |task| %>
  <li>
    <% if task.completed == true %>
  <i class="far fa-check-square"></i>
<% else %>
  <i class="far fa-square"></i>
<%end%>
    <%= link_to task.title, task_path(task) %>
  <% end %>
  </li>
</ul>


<%= link_to "Create Task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Edit Task</h1>
<h2><%= @task.title %></h2>

<p>Details : <%= @task.details %></p>

<% if @task.completed == true %>
  Checked: <i class="far fa-check-square"></i>
<% else %>
  Checked: <i class="far fa-square"></i>
<%end%>
<ul>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
</p>


<p><%= link_to "Back to list", "/tasks"  %></p>